const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const name='blink-pb0-gate-2026-09-18';
const dest=path.join(root,name);
if(!fs.statSync(dest).isDirectory())throw new Error('Existing delivery folder required; firmware is not generated by this tool');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function firmwareFiles(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const p=path.join(dir,e.name);return e.isDirectory()?firmwareFiles(p):/\.(hex|bin|c|h|s|uvprojx|uvoptx)$/i.test(p)?[p]:[];});}
const before=new Map(firmwareFiles(dest).map(p=>[p,hash(p)]));
const files=['index.html','test.html','blink-app.js','package.json','package-lock.json'];
function copy(rel){fs.cpSync(path.join(root,rel),path.join(dest,rel),{recursive:true});}
for(const rel of [...files,'tests','AI-SYNC'])copy(rel);
for(const rel of ['tools/run-page.js','tools/test-all.js','tools/package-release.js'])copy(rel);
for(const [p,digest]of before)if(hash(p)!==digest)throw new Error('Firmware unexpectedly changed: '+p);
const zip=path.join(root,name+'.zip');
const backup=path.join(root,'_backup','release-before-web-sync');
fs.mkdirSync(backup,{recursive:true});
if(fs.existsSync(zip)&&!fs.existsSync(path.join(backup,name+'.zip')))fs.copyFileSync(zip,path.join(backup,name+'.zip'));
const temp=fs.mkdtempSync(path.join(root,'_backup','package-'));
const output=path.join(temp,name+'.zip');
execFileSync('zip',['-qr',output,name,'-x','*/node_modules/*','*/.DS_Store'],{cwd:root});
execFileSync('unzip',['-tq',output]);
for(const rel of files){
 const bytes=execFileSync('unzip',['-p',output,name+'/'+rel],{maxBuffer:16*1024*1024});
 if(!bytes.equals(fs.readFileSync(path.join(root,rel))))throw new Error('Archive mismatch: '+rel);
}
fs.renameSync(output,zip);
console.log('Package: '+zip+'\nSHA256: '+hash(zip)+'\nFirmware files unchanged: '+before.size);
